### ISSUE TITLE
fetch got unexpected key 'KS001'

### ISSUE THREAD

**Issue by Koldar** [Koldar/phdTester#113]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/phdTester/specific_research_field.py", line 1612, in _generate_functions_dict_from_csv
    data_row_converter=data_row_converter,
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/phdTester/specific_research_field.py", line 1653, in __handle_csv_row
    row=csv_outcome,
TypeError: fetch() got an unexpected keyword argument 'ks001'
"""
```

**Comment by Koldar** [comment]
This was an issue of user code, not framework code
