### ISSUE TITLE
Cannot describe without dataframe

### ISSUE THREAD

**Issue by Koldar** [Koldar/phdTester#119]
```
Traceback (most recent call last):
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/path_planning/main.py", line 16, in <module>
    main()
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/path_planning/main.py", line 12, in main
    factory.run(sys.argv[1:])
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/phdTester/specific_research_field.py", line 586, in run
    self.generate_plots(self.__global_settings, self.__under_test_dict_values, self.__test_environment_dict_values)
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/path_planning/factory.py", line 1023, in generate_plots
    time_over_query()
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/path_planning/factory.py", line 1019, in time_over_query
    data_row_converter=OptimalDataRowConverter(),
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/phdTester/specific_research_field.py", line 815, in generate_curves_csvs
    data_row_converter=data_row_converter,
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/phdTester/specific_research_field.py", line 1394, in _generate_curves
    curve_changer=curve_changer
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/phdTester/specific_research_field.py", line 1446, in __handle_curve_changers
    xstatus_new, functions_to_print = cc.alter_curves(functions_to_print)
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/phdTester/curve_changers/curves_changers.py", line 786, in alter_curves
    statistics = curves.get_all_statistics(lower_percentile=self.__lower_percentile, upper_percentile=self.__upper_percentile)
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/phdTester/functions.py", line 509, in get_all_statistics
    description = self._dataframe.describe(percentiles=[lower_percentile, 0.5, upper_percentile])
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/venv/lib/python3.6/site-packages/pandas/core/generic.py", line 9721, in describe
    raise ValueError("Cannot describe a DataFrame without columns")
ValueError: Cannot describe a DataFrame without columns
```

**Comment by Koldar** [comment]
We have given as input an empty IFunctionsDict. I won't fix it because at the moment I don't deal with empty IFunctionsDict. I will fix it when it will be necessary.
