### ISSUE TITLE
function object has no attribute fetch

### ISSUE THREAD

**Issue by Koldar** [Koldar/phdTester#120]
```
Traceback (most recent call last):
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/path_planning/main.py", line 16, in <module>
    main()
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/path_planning/main.py", line 12, in main
    factory.run(sys.argv[1:])
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/phdTester/specific_research_field.py", line 586, in run
    self.generate_plots(self.__global_settings, self.__under_test_dict_values, self.__test_environment_dict_values)
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/path_planning/factory.py", line 1022, in generate_plots
    anytime_avg_solutionratio_over_time()
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/path_planning/factory.py", line 994, in anytime_avg_solutionratio_over_time
    data_row_converter=AnytimeDataRowConverter(),
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/phdTester/specific_research_field.py", line 815, in generate_curves_csvs
    data_row_converter=data_row_converter,
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/phdTester/specific_research_field.py", line 1394, in _generate_curves
    curve_changer=curve_changer
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/phdTester/specific_research_field.py", line 1446, in __handle_curve_changers
    xstatus_new, functions_to_print = cc.alter_curves(functions_to_print)
  File "/home/koldar/git/UNIBS_dynamicPathFinding/phd-tester/phdTester/curve_changers/curves_changers.py", line 360, in alter_curves
    new_function[x] = self.__func.fetch(i, x, curves)
AttributeError: 'function' object has no attribute 'fetch'
```

**Comment by Koldar** [comment]
see #115
